strings = {
    # menu screens
    "gui_title_menu": "====== Menu ======",
    "gui_title_main_menu": "=== Main menu ===",
    "gui_title_system_status": "= System status =",
    "gui_item_direction": "1. Direction",
    "gui_item_route": "2. Route",
    "gui_item_main_menu": "3. Main menu",
    "gui_item_system_status": "1. System status",
    "gui_item_update_mode": "2. Update mode",
    "gui_item_general_config": "1. General config",
    "gui_item_ibis": "2. IBIS",
    "gui_item_network": "3. Network",
    "gui_item_about": "4. About device",
    # info screens
    "gui_title_general_config": "General config",
    "gui_title_ibis": "IBIS",
    "gui_title_network": "Network",
    "gui_title_about": "About device",
    "gui_lbl_yes": "Yes",
    "gui_lbl_no": "No",
    "gui_lbl_not_set": "-",
    "gui_lbl_start_end_stops": "Start/end st.: {}",
    "gui_lbl_short_names": "Short names: {}",
    "gui_lbl_board_info": "Board info: {}",
    "gui_lbl_char_map": "Char map: {}",
    "gui_lbl_tlg_line": "Line: {}",
    "gui_lbl_tlg_dest_number": "Dest.num: {}",
    "gui_lbl_tlg_dest": "Dest.: {}",
    "gui_lbl_tlg_board": "Board: {}",
    "gui_lbl_baudrate": "Baud: {}",
    "gui_lbl_frame": "Frame: {}-{}-{}",
    "gui_lbl_ap_name": "AP: {}",
    "gui_lbl_ap_ip": "IP: {}",
    "gui_lbl_version": "Version: {}",
    "gui_lbl_routes_count": "Routes: {}",
    "gui_lbl_current_route": "Route: {}",
    "gui_lbl_current_trip": "Direction: {:02d}",
}
