strings = {
    "gui_lbl_route": "R:{}",
    "gui_lbl_trip": "D:{:02d}",
    "gui_lbl_trip_code": "C:{}",
    "gui_title_error_code": "Error: {}",
    "gui_lbl_error_prefix": "E:{}",
    "gui_lbl_err_short": "E",
    "gui_lbl_telegrams": "Telegrams: {}",
    "gui_lbl_ver": "ver:{}",
    "gui_msg_ok_hint": "Press OK",
    "gui_msg_initial": "Configuration and routes files need to be loaded",
    "gui_title_update_mode": "Update mode",
    "gui_title_route_menu": "Route",
    "gui_title_trip_menu": "Direction",
    # ibis manager strings
    "ibis_msg_no_route": "Route number is not displayed",
    "ibis_msg_no_trip_code": "Direction code is not displayed",
    "ibis_msg_no_outer_text": "Text on the external display is not shown",
    "ibis_msg_no_inner_text": "Text on the internal display is not shown",
    "ibis_err_unknown_telegram": "Unknown telegram type: {}",
    # web server strings
    # upload page
    "web_title_upload_tab": "Upload",
    "web_lbl_upload_config": "Upload config.json",
    "web_lbl_upload_routes": "Upload routes.ndjson",
    "web_title_update_mode": "Update mode",
    "web_btn_upload": "Upload",
    # success page
    "web_title_success_tab": "Success",
    "web_title_success": "Successfully uploaded",
    "web_lbl_saved_files": "Saved files: {}",
    "web_msg_restart": "Device will restart...",
    # error page
    "web_title_error_tab": "Error",
    "web_title_error": "Error",
    "web_btn_try_again": "Try again",
    "web_err_file_too_big": "File is too large. Maximum: 24KB",
    "web_err_invalid_file_type": "Unsupported file type",
    "web_err_streaming": "Error receiving data: {}",
    "web_err_parsing": "Error processing files: {}",
    "web_err_invalid_format": "Only .json and .ndjson files are allowed: '{}'",
    "web_err_config_content": "Error in config.json: {}",
    "web_err_config_filename": "Invalid filename. Expected a file with 'config' in the name (instead of {})",
    "web_err_routes_content": "Error in routes.ndjson: {}",
    "web_err_routes_filename": "Invalid filename. Expected a file with 'routes' in the name (instead of {})",
    "web_err_no_files": "No files uploaded",
    # file checker strings
    # common
    "fc_more_errors": "... (more errors exist)",
    "fc_at_line": "Line {line_num}: {err}",
    "fc_invalid_encoding": "Invalid file encoding (position {})",
    "fc_invalid_char": "Line {line_num}: Invalid character '{ch}'",
    "fc_missing_colon_after_key": "Missing ':' after key '{}'",
    "fc_missing_value_for_key": "Missing value for key '{}'",
    "fc_missing_comma": "Missing comma between key:value pairs",
    # config file
    "fc_config_file_empty": "Configuration file is empty",
    "fc_config_file_open_error": "Error opening configuration file",
    "fc_config_invalid_json": "Configuration file contains invalid JSON",
    "fc_config_not_json_object": "Configuration file is not a JSON object",
    "fc_duplicate_key": "Duplicate key '{}'",
    "fc_unknown_params": "Unknown parameters: {}",
    "fc_missing_params": "Missing required parameters: {}",
    "fc_param_must_be_string_or_null": "Parameter '{}' must be a string or null",
    "fc_param_must_be_string": "Parameter '{}' must be a string",
    "fc_param_must_not_be_empty": "Parameter '{}' must not be empty",
    "fc_param_must_be_bool": "Parameter '{}' must be true or false",
    "fc_param_must_be_int": "Parameter '{}' must be an integer",
    "fc_expected_key_in_config": "Expected a quoted key in configuration file",
    "fc_unknown_value_for_key": "Unknown value for key '{}'",
    # routes file
    "fc_routes_file_empty": "Routes file is empty",
    "fc_routes_file_open_error": "Error opening routes file",
    "fc_expected_json_object": "Expected a JSON object starting with '{'",
    "fc_expected_key_in_quotes": "Expected a quoted key",
    "fc_expected_string_in_list": "Expected a string in the list for key '{}'",
    "fc_unclosed_list": "Unclosed list for key '{}'",
    "fc_missing_comma_in_list": "Missing comma in list for key '{}'",
    "fc_routes_invalid_json": "Line {}: Invalid JSON",
    "fc_duplicate_route_key": "Line {line_num}: Duplicate key '{key}'",
    "fc_id_and_did_both": "Line {}: Record contains both 'id' and 'did'",
    "fc_unknown_record_type": "Line {}: Unknown record type (no 'id' or 'did')",
    "fc_unknown_fields": "Line {line_num}: Unknown fields: {fields}",
    "fc_duplicate_route_id": "Line {line_num}: Duplicate route id '{route_id}'",
    "fc_duplicate_dir_index": "Line {line_num}: Duplicate direction index '{p_id}'",
    "fc_route_has_no_dirs": "Line {}: Route has no directions",
    "fc_direction_without_route": "Line {}: Direction without a route header",
    "fc_direction_wrong_route": "Line {line_num}: Direction does not belong to the route above it (expected did={did})",
    "fc_field_wrong_data": "Line {line_num}: Field '{field}' has invalid data",
    "fc_missing_field": "Line {line_num}: Missing '{field}'",
    "fc_field_must_be_list": "Line {line_num}: Field '{field}' must be a list",
    "fc_field_must_contain_strings": "Line {line_num}: Field '{field}' must contain only strings",
    # routes and config matching
    "fc_wrong_route_number_format": "Line {line_num}: Route number '{route_number}' is not numeric",
    "routes_config_mismatch": "Routes file does not match configuration: {}",
    # main.py
    "sys_msg_main_loop_error": "Error in main loop: {}",
    "sys_msg_gui_loop_error": "Error in GUI loop: {}",
    # error code messages
    # Config errors
    "E100": "Configuration file not found",
    "E101": "Error writing temp. selection",
    "E102": "Rename config.example to config.json and fill in the parameters",
    "E103": "Error validating configuration file",
    "E104": "Error loading JSON from configuration file",
    "E105": "Error opening configuration file",
    # Routes errors
    "E200": "Routes file not found",
    "E201": "Routes file is empty",
    "E202": "Error opening routes file",
    "E203": "Error validating routes file",
    # IBIS errors
    "E300": "Unknown telegram type",
    "E301": "Route number is missing",
    "E302": "Trip information is missing",
    "E303": "Error loading character table. The char_map.json file must be in the config folder. See readme.",
    "E304": "Stop ID is missing",
    "E305": "Invalid route value",
    "E306": "Invalid stop ID value",
    "E307": "Invalid trip name",
    "E308": "Trip name is missing",
    "E309": "Invalid trip code/route number",
    # Files errors
    "E400": "Language file is missing. The lang.py file must be in the lib folder. See readme.",
    "E401": "Font file is missing. The font.py file must be in the lib folder. See readme.",
    "E402": "Routes file does not match configuration",
    # GUI errors
    "E500": "Unknown menu type: {}",
    # Web server errors
    "E600": "Error stopping web server",
    "E601": "Web server error",
    # Main loop errors
    "E700": "Error in main loop",
    "E701": "Error in GUI loop",
}
